export type CalcResult={metrics:{label:string,value:string}[],note:string};
const n=(v:number)=>Number.isFinite(v)?v:0;
export function pricing(monthlyCustomers:number,currentPrice:number,newPrice:number):CalcResult{const cur=n(monthlyCustomers)*n(currentPrice),next=n(monthlyCustomers)*n(newPrice);return{metrics:[{label:"Current monthly revenue",value:"$"+cur.toFixed(2)},{label:"New monthly revenue",value:"$"+next.toFixed(2)},{label:"Monthly change",value:"$"+(next-cur).toFixed(2)},{label:"Revenue change",value:(cur?(next/cur-1)*100:0).toFixed(1)+"%"}],note:"Scenario model; it does not predict customer churn."}}
export function mrr(startingMrr:number,newRevenue:number,expansion:number,contraction:number,churn:number):CalcResult{const start=n(startingMrr),net=n(newRevenue)+n(expansion)-n(contraction)-n(churn),total=start+net;return{metrics:[{label:"Ending MRR",value:"$"+total.toFixed(2)},{label:"ARR run rate",value:"$"+(total*12).toFixed(2)},{label:"Net MRR change",value:"$"+net.toFixed(2)},{label:"MRR growth",value:(start?(net/start)*100:0).toFixed(1)+"%"}],note:"Ending MRR = starting MRR + new + expansion − contraction − churn."}}
export function arr(mrrValue:number):CalcResult{const m=n(mrrValue);return{metrics:[{label:"ARR",value:"$"+(m*12).toFixed(2)},{label:"Monthly revenue",value:"$"+m.toFixed(2)}],note:"ARR is modeled as MRR × 12."}}
export function churn(startCustomers:number,lostCustomers:number):CalcResult{const s=n(startCustomers),l=n(lostCustomers);return{metrics:[{label:"Customer churn rate",value:(s?(l/s)*100:0).toFixed(2)+"%"},{label:"Customers retained",value:Math.max(0,s-l).toFixed(0)},{label:"Retention rate",value:(s?((s-l)/s)*100:0).toFixed(2)+"%"}],note:"Customer churn uses customers at the start of the period."}}
export function ltv(arpa:number,grossMarginPct:number,monthlyChurnPct:number):CalcResult{const a=n(arpa),g=n(grossMarginPct)/100,c=n(monthlyChurnPct)/100,life=c?1/c:0,value=a*g*life;return{metrics:[{label:"Estimated customer lifetime",value:life.toFixed(1)+" months"},{label:"LTV",value:"$"+value.toFixed(2)},{label:"Monthly gross profit/customer",value:"$"+(a*g).toFixed(2)}],note:"Simple LTV model: ARPA × gross margin ÷ monthly churn."}}
export function cac(salesMarketingSpend:number,newCustomers:number):CalcResult{const spend=n(salesMarketingSpend),customers=n(newCustomers);return{metrics:[{label:"CAC",value:"$"+(customers?spend/customers:0).toFixed(2)},{label:"Spend",value:"$"+spend.toFixed(2)},{label:"New customers",value:customers.toFixed(0)}],note:"CAC = sales and marketing spend ÷ new customers acquired."}}
export function breakeven(fixedCosts:number,price:number,variableCost:number):CalcResult{const fixed=n(fixedCosts),p=n(price),v=n(variableCost),margin=p-v;return{metrics:[{label:"Contribution/customer",value:"$"+margin.toFixed(2)},{label:"Break-even customers",value:(margin>0?Math.ceil(fixed/margin):0).toString()},{label:"Break-even revenue",value:"$"+(margin>0?Math.ceil(fixed/margin)*p:0).toFixed(2)}],note:margin>0?"Fixed costs ÷ contribution margin per customer.":"Price must be above variable cost to reach break-even."}}
export function forecast(startMrr:number,monthlyGrowthPct:number,months:number):CalcResult{let m=n(startMrr),growth=1+n(monthlyGrowthPct)/100;for(let i=0;i<Math.max(0,Math.floor(n(months)));i++)m*=growth;return{metrics:[{label:"Forecast MRR",value:"$"+m.toFixed(2)},{label:"Forecast ARR run rate",value:"$"+(m*12).toFixed(2)},{label:"Total growth",value:(startMrr?(m/startMrr-1)*100:0).toFixed(1)+"%"}],note:"Compounded monthly scenario; actual growth will vary."}}