"use client";

import { useMemo, useState } from "react";
import styles from "../ai-tool.module.css";
import { estimateTokenContext } from "./calculator";

export function TokenContextCalculator(){
 const [text,setText]=useState(""),[charsPerToken,setCpt]=useState(4),[contextWindow,setWindow]=useState(128000),[reservedOutput,setReserved]=useState(2000);
 const r=useMemo(()=>estimateTokenContext({text,charsPerToken,contextWindow,reservedOutput}),[text,charsPerToken,contextWindow,reservedOutput]);
 const num=(setter:(v:number)=>void)=>(e:React.ChangeEvent<HTMLInputElement>)=>setter(Math.max(0,Number(e.target.value)||0));
 return <main className={styles.toolPage}><div className={styles.intro}><p className="eyebrow">TrendForge Tools · AI Utility</p><h1>Token & Context Calculator</h1><p>Estimate token usage from pasted text and see how much of a context window it consumes. The estimate runs entirely in your browser.</p><span className={styles.privacy}>Approximation · no tokenizer API required</span></div>
 <div className={styles.workspace}><section className={styles.panel}><label className={styles.label} htmlFor="token-text">Text to estimate</label><textarea className={styles.textarea} id="token-text" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text, a prompt, or a document excerpt..." /><div className={styles.fieldGrid} style={{marginTop:14}}><label className={styles.field}><span className={styles.label}>Characters / token</span><input className={styles.input} type="number" min=".5" step=".1" value={charsPerToken} onChange={num(setCpt)}/><small>4 is a rough default for English; actual tokenizers vary.</small></label><label className={styles.field}><span className={styles.label}>Context window</span><input className={styles.input} type="number" min="1" value={contextWindow} onChange={num(setWindow)}/></label><label className={styles.field}><span className={styles.label}>Reserved output tokens</span><input className={styles.input} type="number" min="0" value={reservedOutput} onChange={num(setReserved)}/></label></div></section>
 <section className={styles.panel} aria-live="polite"><div className={styles.results}><div className={styles.metric}><span>Estimated tokens</span><strong>{r.estimatedTokens.toLocaleString()}</strong></div><div className={styles.metric}><span>Window use</span><strong>{r.utilization.toFixed(1)}%</strong></div><div className={styles.metric}><span>Input headroom</span><strong>{r.remaining.toLocaleString()}</strong></div></div><div className={styles.findingList}><div className={styles.finding}><strong>Characters</strong><p>{r.characters.toLocaleString()}</p></div><div className={styles.finding}><strong>Words</strong><p>{r.words.toLocaleString()}</p></div><div className={styles.finding}><strong>Input capacity after output reserve</strong><p>{r.availableInput.toLocaleString()} tokens</p></div></div></section></div>
 <div className={styles.help}><section><h2>Use it for planning</h2><p>Test prompts, document excerpts and rough context budgets before choosing a model or designing a RAG flow.</p></section><section><h2>Do not treat it as exact</h2><p>Tokenization differs by model and language. For billing or hard context limits, use the exact tokenizer or provider documentation.</p></section></div></main>;
}