"use client";
import {useState} from "react";import * as T from "./toolkit";import styles from "../ai/ai-tool.module.css";
type Kind="jwt"|"webhook"|"request"|"curl"|"json-ts"|"schema"|"diff"|"regex"|"openapi"|"headers";
const info:Record<Kind,[string,string]>={jwt:["JWT Inspector","Decode JWT header and payload locally and inspect timing claims."],webhook:["Webhook Tester","Send a test webhook request directly from your browser."],request:["API Request Builder","Build and send a browser-side HTTP request."],curl:["cURL → Code","Turn common cURL requests into readable JavaScript fetch code."],"json-ts":["JSON → TypeScript","Generate a TypeScript interface from JSON."],schema:["JSON Schema Generator","Generate a JSON Schema from representative JSON."],diff:["API Response Diff","Compare two JSON responses and highlight changed paths."],regex:["Regex Playground","Test a regular expression against text and inspect matches."],openapi:["OpenAPI Validator","Run lightweight structural checks on OpenAPI JSON."],headers:["HTTP Headers Analyzer","Parse headers and surface practical configuration checks."]};
export function DeveloperTool({kind}:{kind:Kind}){const [input,setInput]=useState(""),[second,setSecond]=useState(""),[url,setUrl]=useState(""),[method,setMethod]=useState("POST"),[headers,setHeaders]=useState("{}"),[pattern,setPattern]=useState(""),[flags,setFlags]=useState("g"),[result,setResult]=useState(""),[error,setError]=useState("");const [title,desc]=info[kind];
const run=async()=>{try{setError("");let out:any;if(kind==="jwt")out=T.decodeJwt(input);else if(kind==="json-ts")out=T.jsonToTs(input);else if(kind==="schema")out=T.generateSchema(input);else if(kind==="diff")out=T.jsonDiff(input,second);else if(kind==="regex")out=T.regexTest(pattern,flags,input);else if(kind==="headers")out=T.analyzeHeaders(input);else if(kind==="curl")out=T.curlToCode(input);else if(kind==="openapi")out=T.validateOpenApi(input);else{const h=headers.trim()?JSON.parse(headers):{};const r=await fetch(url,{method,headers:h,body:["GET","HEAD"].includes(method)?undefined:input});out={status:r.status,statusText:r.statusText,body:(await r.text()).slice(0,4000)};}setResult(typeof out==="string"?out:JSON.stringify(out,null,2));}catch(e){setError(e instanceof Error?e.message:"Unable to process input.");setResult("");}};
return <main className={styles.toolPage}><section className={styles.intro}><p className={styles.privacy}>TrendForge Tools · Developer</p><h1>{title}</h1><p>{desc}</p></section><section className={styles.workspace}>
{["jwt","json-ts","schema","headers","curl","openapi"].includes(kind)?<label className={styles.label}>Input<textarea className={styles.textarea} value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste input here..."/></label>:null}
{kind==="diff"?<div className={styles.panelGrid}><label className={styles.label}>Response A<textarea className={styles.textarea} value={input} onChange={e=>setInput(e.target.value)}/></label><label className={styles.label}>Response B<textarea className={styles.textarea} value={second} onChange={e=>setSecond(e.target.value)}/></label></div>:null}
{kind==="regex"?<div className={styles.panelGrid}><label className={styles.label}>Pattern<input className={styles.input} value={pattern} onChange={e=>setPattern(e.target.value)}/></label><label className={styles.label}>Flags<input className={styles.input} value={flags} onChange={e=>setFlags(e.target.value)}/></label><label className={styles.label}>Test text<textarea className={styles.textarea} value={input} onChange={e=>setInput(e.target.value)}/></label></div>:null}
{kind==="webhook"||kind==="request"?<div className={styles.panel}><div className={styles.fieldGrid}><label className={styles.field}>Method<select className={styles.select} value={method} onChange={e=>setMethod(e.target.value)}>{["GET","POST","PUT","PATCH","DELETE"].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.field}>Endpoint<input className={styles.input} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/endpoint"/></label></div><label className={styles.label}>Headers (JSON)<textarea className={styles.textarea} rows={5} value={headers} onChange={e=>setHeaders(e.target.value)}/></label><label className={styles.label}>Body<textarea className={styles.textarea} rows={8} value={input} onChange={e=>setInput(e.target.value)}/></label></div>:null}
<div className={styles.actions}><button className={styles.button} type="button" onClick={run}>Run</button><button className={styles.button+" "+styles.secondary} type="button" onClick={()=>{setInput("");setSecond("");setResult("");setError("");}}>Reset</button></div>{error?<p className={styles.error}>{error}</p>:null}{result?<div className={styles.panel}><label className={styles.label}>Result</label><pre style={{whiteSpace:"pre-wrap",overflowX:"auto",lineHeight:1.55,fontSize:13}}>{result}</pre><p className={styles.note}>Local transforms stay in your browser. Requests are sent only when you press Run.</p></div>:null}</section></main>}