export function parseJson(input:string):unknown{return JSON.parse(input);}
export function words(s:string){return s.trim()?s.trim().split(/\s+/).length:0;}
export function decodeJwt(token:string){const p=token.trim().split(".");if(p.length!==3)throw new Error("A JWT must contain exactly three dot-separated parts.");const d=(v:string)=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=")),c=>c.charCodeAt(0))));const header=d(p[0]),payload=d(p[1]);const exp=typeof payload.exp==="number"?new Date(payload.exp*1000):null;return{header,payload,expiresAt:exp,expired:exp?exp.getTime()<Date.now():false,hasExpiry:!!exp,signaturePresent:p[2].length>0};}
export function jsonDiff(aInput:string,bInput:string){const a:any=parseJson(aInput),b:any=parseJson(bInput),added:string[]=[],removed:string[]=[],changed:string[]=[];const walk=(x:any,y:any,path="root")=>{if(JSON.stringify(x)===JSON.stringify(y))return;if(x&&y&&typeof x==="object"&&typeof y==="object"&&!Array.isArray(x)&&!Array.isArray(y)){const keys=new Set([...Object.keys(x),...Object.keys(y)]);for(const k of keys){const p=path+"."+k;if(!(k in x))added.push(p);else if(!(k in y))removed.push(p);else walk(x[k],y[k],p);}}else changed.push(path);};walk(a,b);return{added,removed,changed};}
export function jsonToTs(input:string,name="Root"){const v:any=parseJson(input);const seen=new Map<string,string>();const safe=(n:string)=>n.replace(/[^A-Za-z0-9_$]/g,"_").replace(/^\d/,"_");const infer=(x:any,n:string):string=>{if(x===null)return"unknown";if(Array.isArray(x))return x.length?infer(x[0],n+"Item")+"[]":"unknown[]";if(typeof x==="string")return"string";if(typeof x==="number")return"number";if(typeof x==="boolean")return"boolean";if(typeof x==="object"){const tn=safe(n);if(!seen.has(tn)){seen.set(tn,"");const body=Object.entries(x).map(([k,val])=>"  "+JSON.stringify(k)+": "+infer(val,String(k))+";").join("\n");seen.set(tn,"export interface "+tn+" {\n"+body+"\n}");}return tn;}return"unknown";};infer(v,safe(name));return [...seen.values()].filter(Boolean).join("\n\n")||"export type "+safe(name)+" = unknown;";}
export function generateSchema(input:string){const v:any=parseJson(input);const infer=(x:any):any=>{if(x===null)return{type:"null"};if(Array.isArray(x))return{type:"array",items:x.length?infer(x[0]):{}};if(typeof x==="object"){const properties:any={};for(const k of Object.keys(x))properties[k]=infer(x[k]);return{type:"object",properties,required:Object.keys(x)};}return{type:typeof x};};return JSON.stringify({$schema:"https://json-schema.org/draft/2020-12/schema",...infer(v)},null,2);}
export function regexTest(pattern:string,flags:string,input:string){const re=new RegExp(pattern,flags);return[...input.matchAll(re)].map((m,i)=>({index:i,match:m[0],position:m.index??0,groups:m.groups??{}}));}
export function analyzeHeaders(input:string){const headers:Record<string,string>={},invalid:string[]=[],recommendations:string[]=[];for(const row of input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){const i=row.indexOf(":");if(i<1)invalid.push(row);else headers[row.slice(0,i).trim().toLowerCase()]=row.slice(i+1).trim();}if(!headers["content-type"])recommendations.push("Consider declaring Content-Type.");if(!headers["cache-control"])recommendations.push("Review caching policy explicitly.");if(headers["content-type"]?.includes("text/html")&&!headers["x-content-type-options"])recommendations.push("Consider X-Content-Type-Options: nosniff.");return{headers,invalid,recommendations};}
export function curlToCode(input:string){const url=(input.match(/(?:^|\s)(https?:\/\/[^\s'"]+)/)||[])[1]||"";const mm=input.match(/(?:-X|--request)\s+['"]?([A-Z]+)/i);const method=(mm?.[1]||"GET").toUpperCase();const hs=[...input.matchAll(/(?:-H|--header)\s+['"]([^'"]+)['"]/gi)].map(m=>m[1].split(/:\s*(.*)/s));const data=(input.match(/(?:-d|--data|--data-raw)\s+['"]([\s\S]*?)['"](?:\s|$)/i)||[])[1]||"";const obj=Object.fromEntries(hs);let fetch="fetch("+JSON.stringify(url);if(method!=="GET"||data||hs.length)fetch+=", {\n  method: "+JSON.stringify(method)+",\n  headers: "+JSON.stringify(obj)+(data?",\n  body: "+JSON.stringify(data):"")+"\n}";return{url,method,headers:obj,data,fetch:fetch+")"};}
export function validateOpenApi(input:string){const d:any=parseJson(input),errors:string[]=[];if(!d.openapi&&!d.swagger)errors.push("Missing openapi or swagger version.");if(!d.info||typeof d.info!=="object")errors.push("Missing info object.");if(!d.paths||typeof d.paths!=="object")errors.push("Missing paths object.");else for(const p of Object.keys(d.paths))if(!p.startsWith("/"))errors.push("Path "+p+" should start with /.");return{valid:errors.length===0,errors};}