"use client";

import { useMemo, useState } from "react";
import styles from "../ai-tool.module.css";
import { calculateRAGChunks } from "./calculator";

export function RAGChunkingCalculator(){
 const [text,setText]=useState(""),[chunkSize,setChunk]=useState(800),[overlap,setOverlap]=useState(100),[cpt,setCpt]=useState(4);
 const r=useMemo(()=>calculateRAGChunks({text,chunkSize,overlap,charsPerToken:cpt}),[text,chunkSize,overlap,cpt]);
 const update=(setter:(n:number)=>void)=>(e:React.ChangeEvent<HTMLInputElement>)=>setter(Math.max(0,Number(e.target.value)||0));
 return <main className={styles.toolPage}><div className={styles.intro}><p className="eyebrow">TrendForge Tools · AI Utility</p><h1>RAG Chunking Calculator</h1><p>Estimate how many chunks a document will produce and how overlap changes the amount of text processed during retrieval workflows.</p><span className={styles.privacy}>Browser-side estimate · no document upload</span></div>
 <div className={styles.workspace}><section className={styles.panel}><label className={styles.label} htmlFor="rag-text">Document text</label><textarea className={styles.textarea} id="rag-text" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste a representative document or excerpt..." /><div className={styles.fieldGrid} style={{marginTop:14}}><label className={styles.field}><span className={styles.label}>Chunk size (tokens)</span><input className={styles.input} type="number" min="1" value={chunkSize} onChange={update(setChunk)}/></label><label className={styles.field}><span className={styles.label}>Overlap (tokens)</span><input className={styles.input} type="number" min="0" value={overlap} onChange={update(setOverlap)}/></label><label className={styles.field}><span className={styles.label}>Characters / token</span><input className={styles.input} type="number" min=".5" step=".1" value={cpt} onChange={update(setCpt)}/></label></div></section>
 <section className={styles.panel} aria-live="polite"><div className={styles.results}><div className={styles.metric}><span>Estimated chunks</span><strong>{r.chunks.toLocaleString()}</strong></div><div className={styles.metric}><span>Document tokens</span><strong>{r.tokens.toLocaleString()}</strong></div><div className={styles.metric}><span>Overlap</span><strong>{r.overlapTokens.toLocaleString()}</strong></div></div><div className={styles.findingList}><div className={styles.finding}><strong>Last chunk</strong><p>{r.lastChunkTokens.toLocaleString()} estimated tokens</p></div><div className={styles.finding}><strong>Covered chunk capacity</strong><p>{r.coverageTokens.toLocaleString()} tokens including overlap</p></div><div className={styles.finding}><strong>Approximate extra overlap capacity</strong><p>{r.wasteTokens.toLocaleString()} tokens</p></div></div></section></div>
 <div className={styles.help}><section><h2>Experiment with trade-offs</h2><ul><li>Larger chunks can carry more context.</li><li>Overlap can preserve information across boundaries.</li><li>More overlap also increases processed text.</li></ul></section><section><h2>Planning note</h2><p>There is no universal best chunk size. Test retrieval quality with your own documents, embedding model and query distribution.</p></section></div></main>;
}